#!/usr/bin/env python3
"""Write each signer node's federations.toml + tapyrus-signer.toml, ready to
bind-mount into a tapyrus-signerd container at /etc/tapyrus, for a signer set already
generated by generate_dev_secrets.py + sign_genesis.py.

Usage:
    ./scripts/assemble_signer_configs.py <set-name> <threshold> <core-rpc-hosts-file> \\
      <core-rpc-port> <core-rpc-user> <core-rpc-pass> <redis-host> <redis-port> \\
      <addresses-file> [output-dir]

<core-rpc-hosts-file>: one RPC host (container DNS name, e.g. core-1a) per line, N
lines -- each signer gets its OWN core node as RPC target, per the 7-core-node
topology in doc/weekly-integration-test-plan.md section 4b (signer-0 -> core-1a,
signer-1 -> core-2a, signer-2 -> core-3a), not one shared host. Port/user/pass are
shared across all core nodes.

<addresses-file>: one coinbase payout address per line, N lines -- fetch real ones
from each signer's first-layer node's wallet (getnewaddress RPC); doesn't need to
correspond to the signer's own key.

[output-dir] defaults to ./runtime/signers -- writes node-<i>/{federations.toml,tapyrus-signer.toml}.

ROUND_DURATION env var (default 10) sets [general] round-duration in the generated
tapyrus-signer.toml -- the block-pacing interval. The CI workflow always passes
ROUND_DURATION (from the round_duration_seconds workflow input, default 30); use 30
locally too for anything beyond quick iteration: a short duration leaves too little
slack in round_limit_timer = round-duration + round-limit for a round's signing
communication to finish before the next round's messages arrive, producing transient
InvalidBlock / "candidate block is not set" errors (see doc/work-done.md -- round
durations of both 30 and 60 have been verified clean).
"""
import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts.lib.ceremony import CeremonyError, extract_vss_for  # noqa: E402
from scripts.lib.log import log  # noqa: E402

DEFAULT_ROUND_DURATION = "10"
DEFAULT_ROUND_LIMIT = "15"


class SignerConfigAssembler:
    """Builds federations.toml + tapyrus-signer.toml for every node in a signer set.

    Only ever writes a single, always-block-height-0, always-member [[federation]]
    entry -- a rotation needs a second entry appended with a signature field from the
    --xfield handoff. That's handled by a subclass instead of extending this class
    directly: simulate_federation_change.py's RotationSignerConfigAssembler.
    """

    def __init__(self, set_dir, threshold, aggpubkey, core_rpc, redis, round_duration):
        self._set_dir = set_dir
        self._raw_dir = set_dir / "raw"
        self._threshold = threshold
        self._aggpubkey = aggpubkey
        self._core_rpc = core_rpc
        self._redis = redis
        self._round_duration = round_duration

    def run(self, pubkeys, addresses, core_rpc_hosts, output_dir):
        node_count = len(pubkeys)
        for j in range(node_count):
            self._write_node(
                output_dir / f"node-{j}",
                pubkey=pubkeys[j],
                address=addresses[j],
                core_rpc_host=core_rpc_hosts[j],
                node_vss_pubkeys=pubkeys,
            )

    def _write_node(self, node_out_dir, pubkey, address, core_rpc_host, node_vss_pubkeys):
        node_out_dir.mkdir(parents=True, exist_ok=True)
        (node_out_dir / "federations.toml").write_text(
            self._federations_toml(pubkey, node_vss_pubkeys)
        )
        (node_out_dir / "tapyrus-signer.toml").write_text(
            self._signer_toml(pubkey, address, core_rpc_host)
        )

    def _federations_toml(self, pubkey, node_vss_pubkeys):
        vss_lines = ",\n".join(
            f'    "{extract_vss_for(self._raw_dir / f"nodevss_from_{i}.txt", pubkey)}"'
            for i in range(len(node_vss_pubkeys))
        )
        return (
            "[[federation]]\n"
            "block-height = 0\n"
            f"threshold = {self._threshold}\n"
            f'aggregated-public-key = "{self._aggpubkey}"\n'
            "node-vss = [\n"
            f"{vss_lines}\n"
            "]\n"
        )

    def _signer_toml(self, pubkey, address, core_rpc_host):
        return (
            "[general]\n"
            f"round-duration = {self._round_duration}\n"
            f"round-limit = {DEFAULT_ROUND_LIMIT}\n"
            "log-quiet = false\n"
            'log-level = "info"\n'
            "skip-waiting-ibd = true\n"
            "\n"
            "[signer]\n"
            f'to-address = "{address}"\n'
            f'public-key = "{pubkey}"\n'
            'federations-file = "/etc/tapyrus/federations.toml"\n'
            "\n"
            "[rpc]\n"
            f'rpc-endpoint-host = "{core_rpc_host}"\n'
            f"rpc-endpoint-port = {self._core_rpc.port}\n"
            f'rpc-endpoint-user = "{self._core_rpc.user}"\n'
            f'rpc-endpoint-pass = "{self._core_rpc.password}"\n'
            "\n"
            "[redis]\n"
            f'redis-host = "{self._redis.host}"\n'
            f"redis-port = {self._redis.port}\n"
        )


class CoreRpc:
    def __init__(self, port, user, password):
        self.port = port
        self.user = user
        self.password = password


class Redis:
    def __init__(self, host, port):
        self.host = host
        self.port = port


def read_nonempty_lines(path):
    return [line for line in path.read_text().splitlines() if line]


def read_pubkeys(set_dir):
    pubkeys_file = set_dir / "pubkeys.txt"
    if not pubkeys_file.is_file():
        log.error(f"{pubkeys_file} not found -- run generate_dev_secrets.py for this set first")
        sys.exit(1)
    return read_nonempty_lines(pubkeys_file)


def read_matching_lines(path, node_count, description):
    lines = read_nonempty_lines(path)
    if len(lines) != node_count:
        log.error(f"{path} has {len(lines)} {description}, need exactly {node_count} (one per signer)")
        sys.exit(1)
    return lines


def parse_args():
    parser = argparse.ArgumentParser(
        description="Assemble per-node federations.toml + tapyrus-signer.toml for a signer set."
    )
    parser.add_argument("set_name", help="signer set name, already generated by generate_dev_secrets.py")
    parser.add_argument("threshold", type=int, help="signing threshold, same value used for the ceremony")
    parser.add_argument("core_rpc_hosts_file", type=Path, help="one core RPC host per line, N lines")
    parser.add_argument("core_rpc_port")
    parser.add_argument("core_rpc_user")
    parser.add_argument("core_rpc_pass")
    parser.add_argument("redis_host")
    parser.add_argument("redis_port")
    parser.add_argument("addresses_file", type=Path, help="one coinbase payout address per line, N lines")
    parser.add_argument("output_dir", nargs="?", type=Path, default=None, help="default: ./runtime/signers")
    return parser.parse_args()


def main():
    args = parse_args()
    output_dir = args.output_dir or (REPO_ROOT / "runtime" / "signers")
    round_duration = os.environ.get("ROUND_DURATION", DEFAULT_ROUND_DURATION)

    set_dir = REPO_ROOT / "secrets" / args.set_name
    pubkeys = read_pubkeys(set_dir)
    node_count = len(pubkeys)
    addresses = read_matching_lines(args.addresses_file, node_count, "addresses")
    core_rpc_hosts = read_matching_lines(args.core_rpc_hosts_file, node_count, "hosts")
    aggpubkey = (set_dir / "aggregated-public-key.txt").read_text().rstrip("\n")

    log.step(f"assembling signer configs for set '{args.set_name}' ({node_count} nodes)")
    assembler = SignerConfigAssembler(
        set_dir, args.threshold, aggpubkey,
        CoreRpc(args.core_rpc_port, args.core_rpc_user, args.core_rpc_pass),
        Redis(args.redis_host, args.redis_port),
        round_duration,
    )
    assembler.run(pubkeys, addresses, core_rpc_hosts, output_dir)

    last_index = node_count - 1
    log.info(f"done. wrote {output_dir}/node-{{0..{last_index}}}/{{federations.toml,tapyrus-signer.toml}}")


if __name__ == "__main__":
    try:
        main()
    except CeremonyError as exc:
        log.error(str(exc))
        sys.exit(1)
