#!/usr/bin/env python3
"""Run the real tapyrus-setup genesis-signing ceremony (createblockvss -> sign ->
computesig) for a signer set already generated by generate_dev_secrets.py, against an
unsigned genesis block hex.

The unsigned genesis hex itself is NOT produced here -- build it separately with
tapyrus-core's own tool, using the aggpubkey generate_dev_secrets.py already wrote:
    tapyrus-genesis -signblockpubkey=$(cat secrets/<set-name>/aggregated-public-key.txt)
(no -signblockprivatekey -- nobody holds a single private key for a threshold-signed
federation; that's the whole point of this ceremony).

Verified manually end-to-end for 3 signers/threshold 2 (see doc/work-done.md): the
resulting signed genesis was loaded and validated by a real tapyrusd node.

Usage:
    ./scripts/sign_genesis.py <set-name> <unsigned-genesis-hex-file> <output-file> [tapyrus-setup-bin]

Example:
    tapyrus-genesis -signblockpubkey=$(cat secrets/signer-set-a/aggregated-public-key.txt) \\
      > /tmp/unsigned-genesis.hex
    ./scripts/sign_genesis.py signer-set-a /tmp/unsigned-genesis.hex secrets/signer-set-a/genesis.hex

Requires secrets/<set-name>/ to already exist (from generate_dev_secrets.py) --
needs pubkeys.txt, node-<i>/{signer.key,node-secret-share.hex}, and
raw/nodevss_from_<i>.txt from that ceremony.

Required env var: TAPYRUS_SETUP_THRESHOLD=<n> -- the same threshold
generate_dev_secrets.py was run with (not persisted anywhere else, so it must be
passed again explicitly rather than guessed).

GOTCHA (see generate_dev_secrets.py and the plan doc for the full list): computesig
requires --sig/--block-vss/--node-vss to all be the same length as the full signer
count, not just the threshold -- so this script always uses all N signers' local
signatures, even though only `threshold` are cryptographically necessary.
"""
import argparse
import asyncio
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts.lib.ceremony import CeremonyError, TapyrusSetupCeremony, require_executable  # noqa: E402
from scripts.lib.log import log  # noqa: E402

TAPYRUS_SETUP_BUILD_HINT = "(see generate_dev_secrets.py's error message for how to build it)"


class GenesisSigningCeremony(TapyrusSetupCeremony):
    """Runs createblockvss -> sign -> computesig against an already-generated signer
    set and an unsigned genesis block hex.

    Mirrors doc/weekly-integration-test-plan.md section 4a steps 4-7.
    """

    def __init__(self, tapyrus_setup_bin, set_dir, threshold, pubkeys, unsigned_block_hex):
        super().__init__(tapyrus_setup_bin)
        self._set_dir = set_dir
        self._raw_dir = set_dir / "raw"
        self._threshold = threshold
        self._pubkeys = pubkeys
        self._node_count = len(pubkeys)
        self._block = unsigned_block_hex
        self._aggpubkey = (set_dir / "aggregated-public-key.txt").read_text().rstrip("\n")

    async def run(self):
        await self._create_block_vss()
        await self._sign()
        return await self._computesig()

    def _node_dir(self, i):
        return self._set_dir / f"node-{i}"

    def _wif(self, i):
        return (self._node_dir(i) / "signer.key").read_text().rstrip("\n")

    def _node_secret_share(self, i):
        return (self._node_dir(i) / "node-secret-share.hex").read_text().rstrip("\n")

    def _pubkey_args(self):
        return [f"--public-key={pubkey}" for pubkey in self._pubkeys]

    async def _create_block_vss(self):
        log.info("running createblockvss for each signer...")
        outputs = await asyncio.gather(*(
            self._run_setup(
                "createblockvss", *self._pubkey_args(),
                f"--private-key={self._wif(i)}", f"--threshold={self._threshold}",
            )
            for i in range(self._node_count)
        ))
        for i, output in enumerate(outputs):
            (self._raw_dir / f"blockvss_from_{i}.txt").write_text(output)

    async def _sign(self):
        log.info("running sign for each signer...")

        async def sign_one(j):
            pubkey_j = self._pubkeys[j]
            vss_args = [
                f"--block-vss={self._extract_vss_for(self._raw_dir / f'blockvss_from_{i}.txt', pubkey_j)}"
                for i in range(self._node_count)
            ]
            return await self._run_setup(
                "sign", *vss_args,
                f"--aggregated-public-key={self._aggpubkey}",
                f"--node-secret-share={self._node_secret_share(j)}",
                f"--private-key={self._wif(j)}", f"--block={self._block}",
                f"--threshold={self._threshold}",
            )

        local_sigs = await asyncio.gather(*(sign_one(j) for j in range(self._node_count)))
        for j, local_sig in enumerate(local_sigs):
            (self._node_dir(j) / "local-sig-genesis.txt").write_text(local_sig)

    async def _computesig(self):
        # GOTCHA: computesig's --sig/--block-vss/--node-vss arrays must all be the
        # full signer count (not just threshold) -- enforced by an assert_eq! in the
        # source -- so this always passes all N signers' values even though only
        # `threshold` are cryptographically necessary. computesig itself is always run
        # with signer-0's own key material (a "designated signer" -- see plan doc
        # section 4a step 6 for why this is a v1 limitation, not an oversight: it
        # can't be run by a neutral party without borrowing a signer's secrets).
        log.info(f"running computesig (signer 0 combines all {self._node_count} local signatures)...")
        signer0_pubkey = self._pubkeys[0]

        sig_args = [
            f"--sig={(self._node_dir(i) / 'local-sig-genesis.txt').read_text().rstrip(chr(10))}"
            for i in range(self._node_count)
        ]
        blockvss_args = [
            f"--block-vss={self._extract_vss_for(self._raw_dir / f'blockvss_from_{i}.txt', signer0_pubkey)}"
            for i in range(self._node_count)
        ]
        nodevss_args = [
            f"--node-vss={self._extract_vss_for(self._raw_dir / f'nodevss_from_{i}.txt', signer0_pubkey)}"
            for i in range(self._node_count)
        ]

        return await self._run_setup(
            "computesig", *sig_args, *blockvss_args, *nodevss_args,
            f"--aggregated-public-key={self._aggpubkey}",
            f"--node-secret-share={self._node_secret_share(0)}",
            f"--private-key={self._wif(0)}", f"--block={self._block}",
            f"--threshold={self._threshold}",
        )


def default_tapyrus_setup_bin():
    return REPO_ROOT / "workdir" / "tapyrus-signer" / "target" / "release" / "tapyrus-setup"


def parse_args():
    parser = argparse.ArgumentParser(description="Run the genesis-signing half of the tapyrus-setup ceremony.")
    parser.add_argument("set_name", help="signer set name, already generated by generate_dev_secrets.py")
    parser.add_argument("unsigned_genesis_hex_file", type=Path, help="unsigned genesis hex, from tapyrus-genesis")
    parser.add_argument("output_file", type=Path, help="where to write the signed genesis hex")
    parser.add_argument(
        "tapyrus_setup_bin", nargs="?", type=Path, default=None,
        help="path to the tapyrus-setup binary (default: workdir/tapyrus-signer/target/release/tapyrus-setup)",
    )
    return parser.parse_args()


def read_pubkeys(set_dir):
    pubkeys_file = set_dir / "pubkeys.txt"
    if not pubkeys_file.is_file():
        log.error(f"{pubkeys_file} not found -- run generate_dev_secrets.py for this set first")
        sys.exit(1)
    return [line for line in pubkeys_file.read_text().splitlines() if line]


def read_threshold():
    threshold = os.environ.get("TAPYRUS_SETUP_THRESHOLD", "")
    if not threshold:
        log.error(
            "set TAPYRUS_SETUP_THRESHOLD=<n> env var (the same threshold "
            "generate_dev_secrets.py was run with for this set)"
        )
        sys.exit(1)
    return threshold


async def main():
    args = parse_args()
    tapyrus_setup_bin = args.tapyrus_setup_bin or default_tapyrus_setup_bin()
    require_executable(tapyrus_setup_bin, TAPYRUS_SETUP_BUILD_HINT)

    if not args.unsigned_genesis_hex_file.is_file():
        log.error(f"unsigned genesis hex file not found: {args.unsigned_genesis_hex_file}")
        sys.exit(1)

    set_dir = REPO_ROOT / "secrets" / args.set_name
    pubkeys = read_pubkeys(set_dir)
    threshold = read_threshold()
    block = args.unsigned_genesis_hex_file.read_text().rstrip("\n")

    log.step(f"signing genesis for signer set '{args.set_name}'")
    ceremony = GenesisSigningCeremony(tapyrus_setup_bin, set_dir, threshold, pubkeys, block)
    signed_genesis = await ceremony.run()
    args.output_file.write_text(signed_genesis)

    log.info(f"done. signed genesis block written to {args.output_file}")
    log.info(
        "load it via tapyrus/tapyrusd's GENESIS_BLOCK_WITH_SIG env var (see "
        "docker/docker-compose.yml) -- its entrypoint.sh writes it to "
        "<datadir>/genesis.<network_id> itself; see doc/work-done.md"
    )


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except subprocess.CalledProcessError as exc:
        log.error(f"command failed: {' '.join(exc.cmd)}")
        if exc.stderr:
            log.error(exc.stderr.strip())
        sys.exit(1)
    except CeremonyError as exc:
        log.error(str(exc))
        sys.exit(1)
